# Generated by Django 5.2.7 on 2026-10-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControleAtualizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rpa_id", models.IntegerField(verbose_name="RPA")),
                ("execucao_id", models.BigIntegerField(blank=True, null=True)),
                ("modo", models.CharField(max_length=20, verbose_name="Modo")),
                (
                    "periodo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Período"
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="Início")),
                ("fim", models.DateTimeField(verbose_name="Fim")),
                ("inseridos", models.IntegerField(verbose_name="Inseridos")),
                ("atualizados", models.IntegerField(verbose_name="Atualizados")),
                ("ignorados", models.IntegerField(verbose_name="Ignorados")),
                ("falhas", models.IntegerField(verbose_name="Falhas")),
                ("checkpoint", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Controle de Atualização",
                "verbose_name_plural": "Controles de Atualização",
                "db_table": '"rpa"."ControleAtualizacao"',
                "ordering": ["-fim"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "NomeUsuario",
                    models.CharField(max_length=200, verbose_name="Usuário"),
                ),
                (
                    "Modulo",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Módulo"
                    ),
                ),
                ("Acao", models.IntegerField(verbose_name="Ação")),
                (
                    "Descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("Data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "Detalhes",
                    models.JSONField(blank=True, null=True, verbose_name="Detalhes"),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "db_table": '"compartilhado"."Log"',
                "ordering": ["-Data"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_gestao",
                    models.CharField(
                        blank=True, db_column="ID_Gestao", max_length=100, null=True
                    ),
                ),
                (
                    "id_loja",
                    models.CharField(
                        blank=True, db_column="ID_Loja", max_length=10, null=True
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="Nome", max_length=200, null=True
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, db_column="Descricao", max_length=200, null=True
                    ),
                ),
                (
                    "codigointerno",
                    models.CharField(
                        blank=True, db_column="CodigoInterno", max_length=100, null=True
                    ),
                ),
                (
                    "codigobarra",
                    models.CharField(
                        blank=True, db_column="CodigoBarra", max_length=100, null=True
                    ),
                ),
                (
                    "valorvenda",
                    models.DecimalField(
                        blank=True,
                        db_column="ValorVenda",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "valorcusto",
                    models.DecimalField(
                        blank=True,
                        db_column="ValorCusto",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": '"compartilhado"."Produtos"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VendaConfiguracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("Valor", models.CharField(max_length=255, verbose_name="Valor")),
            ],
            options={
                "verbose_name": "Venda Configuração",
                "verbose_name_plural": "Vendas Configurações",
                "db_table": '"vendas"."VendaConfiguracao"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VendaProdutos",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("venda_id", models.BigIntegerField(db_column="Venda_ID")),
                ("nome", models.TextField(db_column="Nome")),
                (
                    "detalhes",
                    models.TextField(blank=True, db_column="Detalhes", null=True),
                ),
                ("quantidade", models.IntegerField(db_column="Quantidade")),
                (
                    "valorcusto",
                    models.DecimalField(
                        db_column="ValorCusto", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "valorvenda",
                    models.DecimalField(
                        db_column="ValorVenda", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "valordesconto",
                    models.DecimalField(
                        db_column="ValorDesconto", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "valortotal",
                    models.DecimalField(
                        db_column="ValorTotal", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "codigoexpedicao",
                    models.CharField(
                        blank=True,
                        db_column="CodigoExpedicao",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda Produto",
                "verbose_name_plural": "Venda Produtos",
                "db_table": '"vendas"."VendaProdutos"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vendas",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_gestao", models.BigIntegerField(db_column="ID_Gestao")),
                ("codigo", models.CharField(db_column="Codigo", max_length=100)),
                (
                    "clientenome",
                    models.CharField(db_column="ClienteNome", max_length=100),
                ),
                (
                    "vendedornome",
                    models.CharField(db_column="VendedorNome", max_length=100),
                ),
                ("data", models.DateField(db_column="Data")),
                (
                    "prazoentrega",
                    models.DateField(blank=True, db_column="PrazoEntrega", null=True),
                ),
                (
                    "situacaonome",
                    models.CharField(db_column="SituacaoNome", max_length=100),
                ),
                (
                    "nomecanalvenda",
                    models.CharField(db_column="NomeCanalVenda", max_length=100),
                ),
                (
                    "condicaopagamento",
                    models.CharField(db_column="CondicaoPagamento", max_length=100),
                ),
                (
                    "valorcusto",
                    models.DecimalField(
                        db_column="ValorCusto", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "valorprodutos",
                    models.DecimalField(
                        db_column="ValorProdutos", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "valordesconto",
                    models.DecimalField(
                        db_column="ValorDesconto", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "valortotal",
                    models.DecimalField(
                        db_column="ValorTotal", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        blank=True, db_column="Origem", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "db_table": '"vendas"."Vendas"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VendasSituacao",
            fields=[
                (
                    "situacaonome",
                    models.CharField(
                        db_column="SituacaoNome",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda Situação",
                "verbose_name_plural": "Vendas Situações",
                "db_table": '"vendas"."VendasSituacao"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vendedores",
            fields=[
                (
                    "nome",
                    models.CharField(
                        db_column="Nome",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "curto",
                    models.CharField(
                        blank=True, db_column="Curto", max_length=50, null=True
                    ),
                ),
                (
                    "percentual",
                    models.IntegerField(blank=True, db_column="Percentual", null=True),
                ),
            ],
            options={
                "verbose_name": "Vendedor",
                "verbose_name_plural": "Vendedores",
                "db_table": '"vendas"."Vendedores"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "Descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "Ativo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Ativo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "db_table": '"dashboard"."Dashboard"',
                "ordering": ["Nome"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard_Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ordem", models.IntegerField(verbose_name="Ordem de Exibição")),
                ("Duracao", models.IntegerField(verbose_name="Duração (segundos)")),
                (
                    "Mensagem",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mensagem"
                    ),
                ),
                (
                    "Dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Configuração",
                "verbose_name_plural": "Dashboard Configurações",
                "db_table": '"dashboard"."Dashboard_Config"',
                "ordering": ["Ordem"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DataHora_Inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora Início"
                    ),
                ),
                (
                    "DataHora_Fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora Fim"
                    ),
                ),
                (
                    "Duracao_Exibida",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duração Exibida (segundos)"
                    ),
                ),
                (
                    "Tipo_Transicao",
                    models.CharField(
                        choices=[
                            ("automatica", "Automática"),
                            ("manual", "Manual"),
                            ("pausa", "Pausado"),
                        ],
                        default="automatica",
                        max_length=20,
                        verbose_name="Tipo de Transição",
                    ),
                ),
                (
                    "Dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Log",
                "verbose_name_plural": "Dashboard Logs",
                "db_table": '"dashboard"."Dashboard_Log"',
                "ordering": ["-DataHora_Inicio"],
            },
        ),
    ]
